name: "Release"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: env

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: "GoReleaser"
        id: go
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        env:
          #GITHUB_TOKEN: ${{ steps.app.outputs.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --clean

      - name: "Debug GoReleaser"
        continue-on-error: true
        env:
          artifacts: ${{ steps.go.outputs.artifacts }}
          metadata: ${{ steps.go.outputs.metadata }}
        run: |
          echo "artifacts: ${artifacts}"
          echo "metadata: ${metadata}"

      - name: "Debug Artifact"
        continue-on-error: true
        shell: bash
        run: ls -lAhR dist

      - name: "Upload to Actions"
        uses: actions/upload-artifact@v6
        with:
          name: client
          path: dist/client

  windows:
    name: "Windows"
    uses: ./.github/workflows/build-windows.yaml
    needs: [build]
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
    permissions:
      contents: write

  linux:
    name: "Linux"
    uses: ./.github/workflows/build-linux.yaml
    needs: [build]
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
    permissions:
      contents: write

  macos:
    name: "macOS"
    uses: ./.github/workflows/build-macos.yaml
    needs: [build]
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
    permissions:
      contents: write

  release:
    name: "Release"
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [windows, linux, macos]

    steps:
      #- name: "Create App Token"
      #  if: ${{ !github.event.release.prerelease }}
      #  id: app
      #  uses: actions/create-github-app-token@v2
      #  with:
      #    app-id: 146360
      #    private-key: ${{ secrets.APP_PRIVATE_KEY }}
      #    owner: smashedr
      #    repositories: homebrew-test
      #
      #- name: "Homebrew Action"
      #  if: ${{ !github.event.release.prerelease }}
      #  uses: cssnr/homebrew-action@master
      #  with:
      #    file: dist/formula/bup.rb
      #    repo: smashedr/homebrew-test
      #    token: ${{ steps.app.outputs.token }}

      - name: "VirusTotal"
        uses: cssnr/virustotal-action@master
        continue-on-error: true
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          collapsed: true

  #check:
  #  name: "Check"
  #  if: ${{ always() }}
  #  runs-on: Ubuntu-latest
  #  timeout-minutes: 5
  #  needs: [release]
  #
  #  steps:
  #    - name: "Alls Green"
  #      uses: re-actors/alls-green@release/v1
  #      with:
  #        jobs: ${{ toJSON(needs) }}
  #        #allowed-failures: docs, linters
  #        allowed-skips: release
  #
  #    - name: "Cleanup Release"
  #      if: ${{ failure() }}
  #      env:
  #        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      run: |
  #        echo -e "\n## Cleanup Release\n\n" >> "$GITHUB_STEP_SUMMARY"
  #        echo -e "Deleting Release and Tag: \`${{ github.ref_name }}\`\n\n" >> "$GITHUB_STEP_SUMMARY"
  #        if gh release delete "${{ github.ref_name }}" --cleanup-tag;then
  #          echo -e "✅ Cleanup Success.\n" >> "$GITHUB_STEP_SUMMARY"
  #        else
  #          echo -e "⛔ Cleanup Failed!\n" >> "$GITHUB_STEP_SUMMARY"
  #        fi
